// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_conv_HH_
#define _matrix_conv_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrix_conv_mac_mbkb.h"

namespace ap_rtl {

struct matrix_conv : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > a_address0;
    sc_out< sc_logic > a_ce0;
    sc_in< sc_lv<8> > a_q0;
    sc_out< sc_lv<4> > b_address0;
    sc_out< sc_logic > b_ce0;
    sc_in< sc_lv<8> > b_q0;
    sc_out< sc_lv<6> > res_address0;
    sc_out< sc_logic > res_ce0;
    sc_out< sc_logic > res_we0;
    sc_out< sc_lv<16> > res_d0;


    // Module declarations
    matrix_conv(sc_module_name name);
    SC_HAS_PROCESS(matrix_conv);

    ~matrix_conv();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    matrix_conv_mac_mbkb<1,1,8,8,16,16>* matrix_conv_mac_mbkb_U1;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > i_1_fu_174_p2;
    sc_signal< sc_lv<4> > i_1_reg_361;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<8> > tmp_10_cast_fu_188_p1;
    sc_signal< sc_lv<8> > tmp_10_cast_reg_366;
    sc_signal< sc_lv<1> > exitcond3_fu_168_p2;
    sc_signal< sc_lv<4> > j_1_fu_198_p2;
    sc_signal< sc_lv<4> > j_1_reg_374;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<2> > m_1_fu_214_p2;
    sc_signal< sc_lv<2> > m_1_reg_382;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<8> > tmp_11_fu_250_p2;
    sc_signal< sc_lv<8> > tmp_11_reg_387;
    sc_signal< sc_lv<1> > exitcond1_fu_208_p2;
    sc_signal< sc_lv<5> > tmp_13_fu_272_p2;
    sc_signal< sc_lv<5> > tmp_13_reg_392;
    sc_signal< sc_lv<2> > n_1_fu_302_p2;
    sc_signal< sc_lv<2> > n_1_reg_400;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > exitcond_fu_296_p2;
    sc_signal< sc_lv<16> > grp_fu_350_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<4> > i_reg_97;
    sc_signal< sc_lv<1> > exitcond2_fu_192_p2;
    sc_signal< sc_lv<4> > j_reg_109;
    sc_signal< sc_lv<16> > sum_reg_121;
    sc_signal< sc_lv<2> > m_reg_134;
    sc_signal< sc_lv<16> > sum_1_reg_145;
    sc_signal< sc_lv<2> > n_reg_157;
    sc_signal< sc_lv<64> > tmp_13_cast_fu_287_p1;
    sc_signal< sc_lv<64> > tmp_19_cast_fu_323_p1;
    sc_signal< sc_lv<64> > tmp_20_cast_fu_337_p1;
    sc_signal< sc_lv<7> > tmp_fu_180_p3;
    sc_signal< sc_lv<4> > m_cast4_fu_204_p1;
    sc_signal< sc_lv<4> > tmp_4_fu_220_p2;
    sc_signal< sc_lv<7> > tmp_9_fu_226_p3;
    sc_signal< sc_lv<5> > tmp_10_fu_238_p3;
    sc_signal< sc_lv<8> > p_shl2_cast_fu_246_p1;
    sc_signal< sc_lv<8> > p_shl1_cast_fu_234_p1;
    sc_signal< sc_lv<4> > tmp_12_fu_260_p3;
    sc_signal< sc_lv<5> > p_shl_cast_fu_268_p1;
    sc_signal< sc_lv<5> > tmp_6_cast_fu_256_p1;
    sc_signal< sc_lv<8> > tmp_2_cast_fu_278_p1;
    sc_signal< sc_lv<8> > tmp_2_fu_282_p2;
    sc_signal< sc_lv<4> > n_cast2_fu_292_p1;
    sc_signal< sc_lv<4> > tmp_8_fu_308_p2;
    sc_signal< sc_lv<8> > tmp_9_cast_fu_314_p1;
    sc_signal< sc_lv<8> > tmp_14_fu_318_p2;
    sc_signal< sc_lv<5> > tmp_1_cast_fu_328_p1;
    sc_signal< sc_lv<5> > tmp_15_fu_332_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_a_address0();
    void thread_a_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_b_address0();
    void thread_b_ce0();
    void thread_exitcond1_fu_208_p2();
    void thread_exitcond2_fu_192_p2();
    void thread_exitcond3_fu_168_p2();
    void thread_exitcond_fu_296_p2();
    void thread_i_1_fu_174_p2();
    void thread_j_1_fu_198_p2();
    void thread_m_1_fu_214_p2();
    void thread_m_cast4_fu_204_p1();
    void thread_n_1_fu_302_p2();
    void thread_n_cast2_fu_292_p1();
    void thread_p_shl1_cast_fu_234_p1();
    void thread_p_shl2_cast_fu_246_p1();
    void thread_p_shl_cast_fu_268_p1();
    void thread_res_address0();
    void thread_res_ce0();
    void thread_res_d0();
    void thread_res_we0();
    void thread_tmp_10_cast_fu_188_p1();
    void thread_tmp_10_fu_238_p3();
    void thread_tmp_11_fu_250_p2();
    void thread_tmp_12_fu_260_p3();
    void thread_tmp_13_cast_fu_287_p1();
    void thread_tmp_13_fu_272_p2();
    void thread_tmp_14_fu_318_p2();
    void thread_tmp_15_fu_332_p2();
    void thread_tmp_19_cast_fu_323_p1();
    void thread_tmp_1_cast_fu_328_p1();
    void thread_tmp_20_cast_fu_337_p1();
    void thread_tmp_2_cast_fu_278_p1();
    void thread_tmp_2_fu_282_p2();
    void thread_tmp_4_fu_220_p2();
    void thread_tmp_6_cast_fu_256_p1();
    void thread_tmp_8_fu_308_p2();
    void thread_tmp_9_cast_fu_314_p1();
    void thread_tmp_9_fu_226_p3();
    void thread_tmp_fu_180_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
